/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-17 08:25:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.project.connectionprovider.ConnectionProvider;
import java.sql.*;

public final class bill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1726294426750L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.project.connectionprovider.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"footer\">\r\n");
      out.write("          <p>All Right Reserved @ BTech Days</p>\r\n");
      out.write("      </div>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bill.css\">\r\n");
      out.write("<title>Bill</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3>Online Shopping Bill</h3>\r\n");
      out.write("<hr>\r\n");

String email = session.getAttribute("email").toString();
int total=0;
try
{
	Connection connection = ConnectionProvider.getConnection();
	Statement statement = connection.createStatement();
	String query1 = "select sum(total) from cart";
	ResultSet rs1 = statement.executeQuery(query1);
	while(rs1.next())
	{
		total=rs1.getInt(1);
	}
	String query2 = "select * from users inner join cart where cart.email='"+email+"' and cart.status='bill'";
	ResultSet rs2 = statement.executeQuery(query2);
	while(rs2.next())
	{

      out.write("\r\n");
      out.write("<div class=\"left-div\"><h3>Name: ");
      out.print(rs2.getString("name") );
      out.write(" </h3></div>\r\n");
      out.write("<div class=\"right-div-right\"><h3>Email:  ");
      out.print(email );
      out.write("</h3></div>\r\n");
      out.write("<div class=\"right-div\"><h3>Mobile Number: ");
      out.print(rs2.getString("mobileNumber") );
      out.write(" </h3></div>  \r\n");
      out.write("\r\n");
      out.write("<div class=\"left-div\"><h3>Order Date: ");
      out.print(rs2.getString("orderDate") );
      out.write(" </h3></div>\r\n");
      out.write("<div class=\"right-div-right\"><h3>Payment Method: ");
      out.print(rs2.getString("paymentMethod") );
      out.write(" </h3></div>\r\n");
      out.write("<div class=\"right-div\"><h3>Expected Delivery: ");
      out.print(rs2.getString("deliveryDate") );
      out.write(" </h3></div> \r\n");
      out.write("\r\n");
      out.write("<div class=\"left-div\"><h3>Transaction Id: ");
      out.print(rs2.getString("transactionId") );
      out.write(" </h3></div>\r\n");
      out.write("<div class=\"right-div-right\"><h3>City:  ");
      out.print(rs2.getString("city") );
      out.write("</h3></div> \r\n");
      out.write("<div class=\"right-div\"><h3>Address: ");
      out.print(rs2.getString("address") );
      out.write(" </h3></div> \r\n");
      out.write("\r\n");
      out.write("<div class=\"left-div\"><h3>State:  ");
      out.print(rs2.getString("state") );
      out.write("</h3></div>\r\n");
      out.write("<div class=\"right-div-right\"><h3>Country:  ");
      out.print(rs2.getString("country") );
      out.write("</h3></div>  \r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
break; }
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("<table id=\"customers\">\r\n");
      out.write("<h3>Product Details</h3>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>S.No</th>\r\n");
      out.write("    <th>Product Name</th>\r\n");
      out.write("    <th>category</th>\r\n");
      out.write("    <th>Price</th>\r\n");
      out.write("    <th>Quantity</th>\r\n");
      out.write("     <th>Sub Total</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("    ");

  int sno=0;
  ResultSet rs3 = statement.executeQuery("select * from cart inner join product where cart.product_id=product.id and cart.status='bill'");
  while(rs3.next())
  {
	  sno=sno+1;
  
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>");
      out.print(sno );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs3.getString("name") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs3.getString("category") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs3.getString("price") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs3.getString("quantity") );
      out.write("</td>\r\n");
      out.write("     <td>");
      out.print(rs3.getString("total") );
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<h3>Total: ");
      out.print(total );
      out.write("</h3>\r\n");
      out.write("<a href=\"continueShopping.jsp\"><button class=\"button left-button\">Continue Shopping</button></a>\r\n");
      out.write("<a onclick=\"window.print();\"><button class=\"button right-button\">Print</button></a>\r\n");
      out.write("<br><br><br><br>\r\n");

}
	catch(Exception e)
	{
		e.printStackTrace();
	}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
